export var data = [
  {
    name: "Property One",
    type: "House",
    price: 2050,
    address: "lane one,street one",
    city: "city one",
    bookedFrom: new Date(2022, 9, 15),
    bookedTo: new Date(2022, 9, 17),
    favourite: true,
    image: "./estate/estate1.jpg",
  },
  {
    name: "Property Two",
    type: "Hotel",
    price: 1800,
    address: "lane two,street two",
    city: "city one",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 15),
    favourite: false,
    image: "./estate/estate2.jpg",
  },
  {
    name: "Property Three",
    type: "House",
    price: 1600,
    address: "lane Three,street Three",
    city: "city one",
    bookedFrom: new Date(2022, 9, 17),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate3.jpg",
  },
  {
    name: "Property Four",
    type: "Resort",
    price: 3200,
    address: "lane Four,street Four",
    city: "city one",
    bookedFrom: new Date(),
    bookedTo: new Date(),
    favourite: true,
    image: "./estate/estate4.jpg",
  },
  {
    name: "Property Five",
    type: "Resort",
    price: 3600,
    address: "lane Five,street Five",
    city: "city one",
    bookedFrom: new Date(2022, 9, 15),
    bookedTo: new Date(2022, 9, 17),
    favourite: false,
    image: "./estate/estate5.jpg",
  },
  {
    name: "Property Six",
    type: "Hotel",
    price: 2800,
    address: "lane Six,street Six",
    city: "city two",
    bookedFrom: new Date(2022, 9, 16),
    bookedTo: new Date(2022, 9, 17),
    favourite: false,
    image: "./estate/estate6.jpg",
  },
  {
    name: "Property Seven",
    type: "Hotel",
    price: 1200,
    address: "lane Seven,street Seven",
    city: "city two",
    bookedFrom: new Date(2022, 9, 19),
    bookedTo: new Date(2022, 9, 20),
    favourite: false,
    image: "./estate/estate7.jpg",
  },
  {
    name: "Property Eight",
    type: "House",
    price: 2100,
    address: "lane Eight,street Eight",
    city: "city two",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate8.jpg",
  },
  {
    name: "Property Nine",
    type: "House",
    price: 3300,
    address: "lane Nine,street Nine",
    city: "city two",
    bookedFrom: new Date(),
    bookedTo: new Date(),
    favourite: false,
    image: "./estate/estate9.jpg",
  },
  {
    name: "Property Ten",
    type: "Resort",
    price: 2250,
    address: "lane Ten,street Ten",
    city: "city two",
    bookedFrom: new Date(),
    bookedTo: new Date(),
    favourite: false,
    image: "./estate/estate10.jpg",
  },

  {
    name: "Property Eleven",
    type: "Hotel",
    price: 4100,
    address: "lane Eleven,street Eleven",
    city: "city three",
    bookedFrom: new Date(2022, 9, 16),
    bookedTo: new Date(2022, 9, 17),
    favourite: false,
    image: "./estate/estate11.jpg",
  },
  {
    name: "Property Twelve",
    type: "Hotel",
    price: 4500,
    address: "lane Twelve,street Twelve",
    city: "city three",
    bookedFrom: new Date(2022, 9, 19),
    bookedTo: new Date(2022, 9, 20),
    favourite: false,
    image: "./estate/estate12.jpg",
  },
  {
    name: "Property Thirteen",
    type: "House",
    price: 1300,
    address: "lane Thirteen,street Thirteen",
    city: "city three",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate13.jpg",
  },
  {
    name: "Property Fourteen",
    type: "House",
    price: 1700,
    address: "lane Fourteen,street Fourteen",
    city: "city three",
    bookedFrom: new Date(2022, 9, 20),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate14.jpg",
  },
  {
    name: "Property Fifteen",
    type: "Resort",
    price: 4200,
    address: "lane Fifteen,street Fifteen",
    city: "city three",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 14),
    favourite: false,
    image: "./estate/estate15.jpg",
  },
];
export const setFav = (name) => {
  let dataindex;
  data.every((item, index) => {
    if (item.name.includes(name)) {
      dataindex = index;
      return false;
    } else {
      return true;
    }
  });
  data[dataindex].favourite = true ? false : false;
  return data;
};
export const getData = () => {
  return data;
};
