export var data = [
  {
    name: "Cascade South",
    type: "House",
    price: 2050,
    address: "lane one,street one",
    city: "city one",
    bookedFrom: new Date(2022, 9, 15),
    bookedTo: new Date(2022, 9, 17),
    favourite: true,
    image: "./estate/estate1.jpg",
  },
  {
    name: "Citylife Homes",
    type: "Hotel",
    price: 1800,
    address: "lane two,street two",
    city: "city one",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 15),
    favourite: false,
    image: "./estate/estate2.jpg",
  },
  {
    name: "Keyhole Nest",
    type: "House",
    price: 1600,
    address: "lane Three,street Three",
    city: "city one",
    bookedFrom: new Date(2022, 9, 17),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate3.jpg",
  },
  {
    name: "Imperial Realty",
    type: "Resort",
    price: 3200,
    address: "lane Four,street Four",
    city: "city one",
    bookedFrom: new Date(),
    bookedTo: new Date(),
    favourite: true,
    image: "./estate/estate4.jpg",
  },
  {
    name: "Granite Marvel",
    type: "Resort",
    price: 3600,
    address: "lane Five,street Five",
    city: "city one",
    bookedFrom: new Date(2022, 9, 15),
    bookedTo: new Date(2022, 9, 17),
    favourite: false,
    image: "./estate/estate5.jpg",
  },
  {
    name: "Castello",
    type: "Hotel",
    price: 2800,
    address: "lane Six,street Six",
    city: "city two",
    bookedFrom: new Date(2022, 9, 16),
    bookedTo: new Date(2022, 9, 17),
    favourite: false,
    image: "./estate/estate6.jpg",
  },
  {
    name: "Hungry Den",
    type: "Hotel",
    price: 1200,
    address: "lane Seven,street Seven",
    city: "city two",
    bookedFrom: new Date(2022, 9, 19),
    bookedTo: new Date(2022, 9, 20),
    favourite: false,
    image: "./estate/estate7.jpg",
  },
  {
    name: "Honor Medal",
    type: "House",
    price: 2100,
    address: "lane Eight,street Eight",
    city: "city two",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate8.jpg",
  },
  {
    name: "Sunshine peak",
    type: "House",
    price: 3300,
    address: "lane Nine,street Nine",
    city: "city two",
    bookedFrom: new Date(),
    bookedTo: new Date(),
    favourite: false,
    image: "./estate/estate9.jpg",
  },
  {
    name: "Oak Castle",
    type: "Resort",
    price: 2250,
    address: "lane Ten,street Ten",
    city: "city two",
    bookedFrom: new Date(),
    bookedTo: new Date(),
    favourite: false,
    image: "./estate/estate10.jpg",
  },

  {
    name: "Sterling one",
    type: "Hotel",
    price: 4100,
    address: "lane Eleven,street Eleven",
    city: "city three",
    bookedFrom: new Date(2022, 9, 16),
    bookedTo: new Date(2022, 9, 17),
    favourite: false,
    image: "./estate/estate11.jpg",
  },
  {
    name: "Urban Castle",
    type: "Hotel",
    price: 4500,
    address: "lane Twelve,street Twelve",
    city: "city three",
    bookedFrom: new Date(2022, 9, 19),
    bookedTo: new Date(2022, 9, 20),
    favourite: false,
    image: "./estate/estate12.jpg",
  },
  {
    name: "Cement City",
    type: "House",
    price: 1300,
    address: "lane Thirteen,street Thirteen",
    city: "city three",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate13.jpg",
  },
  {
    name: "Soho Bytes",
    type: "House",
    price: 1700,
    address: "lane Fourteen,street Fourteen",
    city: "city three",
    bookedFrom: new Date(2022, 9, 20),
    bookedTo: new Date(2022, 9, 21),
    favourite: false,
    image: "./estate/estate14.jpg",
  },
  {
    name: "Luxury Abodes",
    type: "Resort",
    price: 4200,
    address: "lane Fifteen,street Fifteen",
    city: "city three",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 14),
    favourite: false,
    image: "./estate/estate15.jpg",
  },
  {
    name: "Vintage Boom",
    type: "House",
    price: 4800,
    address: "lane sixteen,street sixteen",
    city: "city four",
    bookedFrom: new Date(2022, 9, 20),
    bookedTo: new Date(2022, 9, 22),
    favourite: false,
    image: "./estate/estate16.jpg",
  },
  {
    name: "Bahamas Hotel",
    type: "Hotel",
    price: 3900,
    address: "lane seventeen,street seventeen",
    city: "city four",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 17),
    favourite: true,
    image: "./estate/estate17.jpg",
  },
  {
    name: "Nighmare Hell",
    type: "Hotel",
    price: 3750,
    address: "lane eighteen,street eighteen",
    city: "city four",
    bookedFrom: new Date(2022, 9, 13),
    bookedTo: new Date(2022, 9, 14),
    favourite: false,
    image: "./estate/estate18.jpg",
  },
  {
    name: "Villain Den",
    type: "Resort",
    price: 2400,
    address: "lane nineteen,street nineteen",
    city: "city four",
    bookedFrom: new Date(2022, 9, 15),
    bookedTo: new Date(2022, 9, 16),
    favourite: false,
    image: "./estate/estate1.jpg",
  },
  {
    name: "World One",
    type: "House",
    price: 2050,
    address: "lane twenty,street twenty",
    city: "city four",
    bookedFrom: new Date(2022, 9, 16),
    bookedTo: new Date(2022, 9, 17),
    favourite: true,
    image: "./estate/estate20.jpg",
  },
];
export const setFav = (name) => {
  let dataindex;
  data.every((item, index) => {
    if (item.name.includes(name)) {
      dataindex = index;
      return false;
    } else {
      return true;
    }
  });
  data[dataindex].favourite = true ? false : false;
  return data;
};
export const getData = () => {
  return data;
};
